/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DDocIdIndexRouteImport } from './routes/d/$docId/index'
import { Route as DDocIdCreatedIndexRouteImport } from './routes/d/$docId/created/index'

const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DDocIdIndexRoute = DDocIdIndexRouteImport.update({
  id: '/d/$docId/',
  path: '/d/$docId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DDocIdCreatedIndexRoute = DDocIdCreatedIndexRouteImport.update({
  id: '/d/$docId/created/',
  path: '/d/$docId/created/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/d/$docId/': typeof DDocIdIndexRoute
  '/d/$docId/created/': typeof DDocIdCreatedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/d/$docId': typeof DDocIdIndexRoute
  '/d/$docId/created': typeof DDocIdCreatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/d/$docId/': typeof DDocIdIndexRoute
  '/d/$docId/created/': typeof DDocIdCreatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create' | '/d/$docId/' | '/d/$docId/created/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create' | '/d/$docId' | '/d/$docId/created'
  id: '__root__' | '/' | '/create' | '/d/$docId/' | '/d/$docId/created/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  DDocIdIndexRoute: typeof DDocIdIndexRoute
  DDocIdCreatedIndexRoute: typeof DDocIdCreatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$docId/': {
      id: '/d/$docId/'
      path: '/d/$docId'
      fullPath: '/d/$docId/'
      preLoaderRoute: typeof DDocIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$docId/created/': {
      id: '/d/$docId/created/'
      path: '/d/$docId/created'
      fullPath: '/d/$docId/created/'
      preLoaderRoute: typeof DDocIdCreatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  DDocIdIndexRoute: DDocIdIndexRoute,
  DDocIdCreatedIndexRoute: DDocIdCreatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
